export default {
   
    /*EXTERNAL_USER_API:"/matrimony/user/external/",
    USER_REGISTER_API:"/matrimony/user/register/",
    USER_PROFILE_API:"/matrimony/user/profile/",
    USER_PERSONAL_PROFILE_API:"/matrimony/user/profile/personal",
    USER_LOCATION_API:"/matrimony/user/profile/location",
    USER_RELIGION_API:"/matrimony/user/profile/religion",
    USER_PROF_API:"/matrimony/user/profile/professional",
    USER_COMPLETE_PROFILE_API:"/matrimony/user/completeprofile/",
    USER_PROFILE_IMAGE_API:"/matrimony/user/image/",
    USER_PROFILE_HOROSCOPE_API:"/matrimony/user/horoscope/",
    QUICK_SEARCH_API:"/matrimony/user/list/",
    USER_API:"/matrimony/user/",
    USER_API_SELF:"/matrimony/user/self/",
    CONTACT_API:"/matrimony/contact/list",
    PROFILE_LIST_API:"/matrimony/featuredprofiles/list",
    PREFERENCE_API:"/matrimony/preference/",
    VISITED_PROFILE_LIST:"/matrimony/visitedprofiles/list/",
    SHORT_LISTED_PROFILE_LIST:"/matrimony/shortlisted/list/",
    SHORT_LISTED_PROFILE:"/matrimony/shortlisted/",
    BLOCKED_PROFILE_LIST:"/matrimony/blocked/list/",
    BLOCKED_PROFILE:"/matrimony/blocked/",
    UN_BLOCK_PROFILE:"/matrimony/blocked/unblock/",
    USER_LOGIN:"/matrimony/user/login/"
    
    */ 
  
 
   USER_REGISTER_API:"http://localhost:8085/matrimony/identity/register/",
   USER_PROFILE_API:"http://localhost:8085/matrimony/user/profile/",
   USER_PERSONAL_PROFILE_API:"http://localhost:8085/matrimony/user/profile/personal",
   USER_LOCATION_API:"http://localhost:8085/matrimony/user/profile/location",
   USER_RELIGION_API:"http://localhost:8085/matrimony/user/profile/religion",
   USER_PROF_API:"http://localhost:8085/matrimony/user/profile/professional",
   USER_COMPLETE_PROFILE_API:"http://localhost:8085/matrimony/user/completeprofile/",
   USER_PROFILE_IMAGE_API:"http://localhost:8085/matrimony/user/image/",
   USER_PROFILE_HOROSCOPE_API:"http://localhost:8085/matrimony/user/horoscope/",
   QUICK_SEARCH_API:"http://localhost:8085/matrimony/user/list/",
   USER_API:"http://localhost:8085/matrimony/user/",
   USER_API_SELF:"http://localhost:8085/matrimony/user/self/",
   CONTACT_API:"http://localhost:8085/matrimony/contact/list",
   PROFILE_LIST_API:"http://localhost:8085/matrimony/featuredprofiles/list",
   PREFERENCE_API:"http://localhost:8085/matrimony/preference/",
   VISITED_PROFILE_LIST:"http://localhost:8085/matrimony/visitedprofiles/list/",
   SHORT_LISTED_PROFILE_LIST:"http://localhost:8085/matrimony/shortlisted/list/",
   SHORT_LISTED_PROFILE:"http://localhost:8085/matrimony/shortlisted/",
   BLOCKED_PROFILE_LIST:"http://localhost:8085/matrimony/blocked/list/",
   BLOCKED_PROFILE:"http://localhost:8085/matrimony/blocked/",   
   UN_BLOCK_PROFILE:"http://localhost:8085/matrimony/blocked/unblock/",
   USER_LOGIN:"http://localhost:8085/matrimony/identity/login/"
 }; 