export default {
   
   MESSAGE_STATUS_PENDING:"P",
   MESSAGE_STATUS_DECLINED:"D",
   MESSAGE_STATUS_ACCEPTED:"A",
   MESSAGE_STATUS_AWAITING_REPLY:"R",
   MESSAGE_STATUS_ALL:"L",
   USER_FIRST_NAME:"firstName",
   USER_LAST_NAME:"lastName",
   USER_GENDER:"gender",
   USER_ID_TOKEN:"idToken",
   USER_REFERESH_TOKEN:"refreshToken",
   USER_ACCESS_TOKEN:"accessToken",
   USER_PROFILE_ID:"profileId",
   USER_NAME:"username",
   PROFILE_PERCENT_COMP:"percentageCompeleted",
   YES:"YES",
   NO:"NO",
   SUCCESS_MESSAGE_CODE_200:200,
   ERR_MESSAGE_CODE_400:400,
   toastIdErr:400,
   toastIdSuccess:100,
   genderM:"M",
   genderF:"F",
   ageFrom:18,
   RELIGION_HINDU:"H",
   ageTo:40,
   minHeight:'121',
   maxHeight:'213',
   mStatus_NM:[{value:'NM',label:"Never Married"}],
   dropdownDefault:"--Select--",
   regilionValues :[
      { value: "1", label: "Hindu" },
      { value: "2", label: "Buddhist" },      
      { value: "3", label: "Christian" },
      { value: "4", label: "Muslim - Shia" },
      { value: "5", label: "Muslim - Sunni" },
      { value: "6", label: "Muslim - Others" },
      { value: "7", label: "Sikh" },
      { value: "8", label: "Jain - Digambar" },
      { value: "9", label: "Jain - Shwetambar" },
      { value: "10", label: "Jain - Others" },
      { value: "11", label: "Parsi" },
      { value: "12", label: "Inter-Religion" }
   ],
   gothramValues :[
      { value: "1", label: "Anuradha / Anusham / Anizham" },
      { value: "2", label: "Ardra / Thiruvathira" },
      { value: "3", label: "Ashlesha / Ayilyam" },
      { value: "4", label: "Ashwini / Ashwathi" },
      { value: "5", label: "Bharani" },
      { value: "6", label: "Chitra / Chitha" },
      { value: "7", label: "Dhanista / Avittam" },
      { value: "8", label: "Hastha / Atham" },
      { value: "9", label: "Jyesta / Kettai" },
      { value: "10", label: "Kettai" },
      { value: "11", label: "Krithika / Karthika" },
      { value: "12", label: "Makha / Magam" },
      { value: "13", label: "Moolam / Moola" },
      { value: "14", label: "Mrigasira / Makayiram" },
      { value: "15", label: "Poorvabadrapada / Puratathi" },
      { value: "16", label: "Poorvapalguni / Puram / Pubbhe" },
      { value: "17", label: "Poorvashada / Pooradam" },
      { value: "18", label: "Punarvasu / Punarpusam" },
      { value: "19", label: "Pushya / Poosam / Pooyam" },
      { value: "20", label: "Revathi" },
      { value: "21", label: "Rohini" },
      { value: "22", label: "Shatataraka / Sadayam / Satabishek" },
      { value: "23", label: "Shravan / Thiruvonam" },
      { value: "24", label: "Swati / Choth" },
      { value: "25", label: "Uthram" },
      { value: "26", label: "Uttarabadrapada / Uthratadhi" },
      { value: "27", label: "Uttarapalguni / UthramUttarashada / Uthradam" },
      { value: "28", label: "Vishaka / Vishakam" },
   ],
   maritalStatusValues :[
      { value: "NM", label: "Never Married" },
      { value: "WD", label: "Widowed" },
      { value: "DD", label: "Divorced" },
      { value: "AD", label: "Awaiting Divorce" }
   ],
   customSelectStyles : {     
      control: () => ({
        maxHeight:30,
        minHeight:30
      })     
    }
};