export default {

    countries :[
        { value: "IND", label: "India" },
        { value: "USA", label: "United States of America" },
        { value: "GBR", label: "United Kingdom" } 
    ],
    indiaStates : [
         { value: 2, label: "Arunachal Pradesh" },
         { value: 4, label: "Assam" },
         { value: 6, label: "Bihar" },
         { value: 8, label: "Chandigarh" },
         { value: 10, label: "Chhattisgarh" },
         { value: 12, label: "Dadra and Nagar Haveli" },
         { value: 14, label: "Daman and Diu" },
         { value: 16, label: "Delhi" },
         { value: 18, label: "Goa" },
         { value: 20, label: "Gujarat" },
         { value: 22, label: "Haryana" },
         { value: 24, label: "Himachal Pradesh" },
         { value: 26, label: "Jammu and Kashmir" },
         { value: 28, label: "Jharkhand" },
         { value: 30, label: "Karnataka" },
         { value: 32, label: "Kerala" },
         { value: 34, label: "Lakshadweep" },
         { value: 36, label: "Madhya Pradesh" },
         { value: 38, label: "Maharashtra" },
         { value: 40, label: "Manipur" },
         { value: 42, label: "Meghalaya" },
         { value: 44, label: "Mizoram" },
         { value: 46, label: "Nagaland" },
         { value: 48, label: "Odisha" },
         { value: 50, label: "Puducherry" },
         { value: 52, label: "Punjab" },
         { value: 54, label: "Rajasthan" },
         { value: 56, label: "Sikkim" },
         { value: 58, label: "Tamil Nadu" },
         { value: 60, label: "Telangana" },
         { value: 62, label: "Tripura" },
         { value: 64, label: "Uttar Pradesh" },
         { value: 66, label: "Uttarakhand" },
         { value: 68, label: "West Bengal" }
     ],
     tamilnaduDistricts :[
        { value: 0, label: "--Select--" },
        { value: 1, label: "Ariyalur" },
        { value: 2, label: "Chennai" },  
        { value: 3, label: "Coimbatore" },  
        { value: 4, label: "Cuddalore" },  
        { value: 5, label: "Dharmapuri" },  
        { value: 6, label: "Dindigul" },  
        { value: 7, label: "Erode" }, 
        { value: 8, label: "Kanchipuram" },  
        { value: 9, label: "Kanyakumari" },  
        { value: 10, label: "Karur" },  
        { value: 11, label: "Krishnagiri" },  
        { value: 12, label: "Madurai" },  
        { value: 13, label: "Nagapattinam" },  
        { value: 14, label: "Namakkal" },  
        { value: 15, label: "Nilgiris" },  
        { value: 16, label: "Perambalur" },
        { value: 17, label: "Pudukkottai" },
        { value: 18, label: "Ramanathapuram" },
        { value: 19, label: "Salem" },
        { value: 20, label: "Sivagangai" },
        { value: 21, label: "Thanjavur" },
        { value: 22, label: "Theni" },
        { value: 23, label: "Thoothukudi" },
        { value: 24, label: "Tiruchirappalli" },
        { value: 25, label: "Tirunelveli" },
        { value: 26, label: "Tiruppur" },
        { value: 27, label: "Tiruvallur" },
        { value: 28, label: "Tiruvannamalai" },
        { value: 29, label: "Tiruvarur" },
        { value: 30, label: "Vellore" },
        { value: 31, label: "Viluppuram" },
        { value: 32, label: "Virudunagar" }
       ],
}