export default {

    countries :[
        { value:"", label: "--Select--"},
        { value:"AF", label: "Afghanistan"},
        { value:"AX", label: "Aland Islands"},
        { value:"AL", label: "Albania"},
        { value:"DZ", label: "Algeria"},
        { value:"AS", label: "American Samoa"},
        { value:"AD", label: "Andorra"},
        { value:"AO", label: "Angola"},
        { value:"AI", label: "Anguilla"},
        { value:"AQ", label: "Antarctica"},
        { value:"AG", label: "Antigua and Barbuda"},
        { value:"AR", label: "Argentina"},
        { value:"AM", label: "Armenia"},
        { value:"AW", label: "Aruba"},
        { value:"AU", label: "Australia"},
        { value:"AT", label: "Austria"},
        { value:"AZ", label: "Azerbaijan"},
        { value:"BS", label: "Bahamas"},
        { value:"BH", label: "Bahrain"},
        { value:"BD", label: "Bangladesh"},
        { value:"BB", label: "Barbados"},
        { value:"BY", label: "Belarus"},
        { value:"BE", label: "Belgium"},
        { value:"BZ", label: "Belize"},
        { value:"BJ", label: "Benin"},
        { value:"BM", label: "Bermuda"},
        { value:"BT", label: "Bhutan"},
        { value:"BO", label: "Bolivia"},
        { value:"BA", label: "Bosnia and Herzegovina"},
        { value:"BW", label: "Botswana"},
        { value:"BV", label: "Bouvet Island"},
        { value:"BR", label: "Brazil"},
        { value:"VG", label: "British Virgin Islands"},
        { value:"IO", label: "British Indian Ocean Territory"},
        { value:"BN", label: "Brunei Darussalam"},
        { value:"BG", label: "Bulgaria"},
        { value:"BF", label: "Burkina Faso"},
        { value:"BI", label: "Burundi"},
        { value:"KH", label: "Cambodia"},
        { value:"CM", label: "Cameroon"},
        { value:"CA", label: "Canada"},
        { value:"CV", label: "Cape Verde"},
        { value:"KY", label: "Cayman Islands"},
        { value:"CF", label: "Central African Republic"},
        { value:"TD", label: "Chad"},
        { value:"CL", label: "Chile"},
        { value:"CN", label: "China"},
        { value:"HK", label: "Hong Kong, SAR China"},
        { value:"MO", label: "Macao, SAR China"},
        { value:"CX", label: "Christmas Island"},
        { value:"CC", label: "Cocos (Keeling) Islands"},
        { value:"CO", label: "Colombia"},
        { value:"KM", label: "Comoros"},
        { value:"CG", label: "Congo (Brazzaville)"},
        { value:"CD", label: "Congo, (Kinshasa)"},
        { value:"CK", label: "Cook Islands"},
        { value:"CR", label: "Costa Rica"},
        { value:"CI", label: "Côte d'Ivoire"},
        { value:"HR", label: "Croatia"},
        { value:"CU", label: "Cuba"},
        { value:"CY", label: "Cyprus"},
        { value:"CZ", label: "Czech Republic"},
        { value:"DK", label: "Denmark"},
        { value:"DJ", label: "Djibouti"},
        { value:"DM", label: "Dominica"},
        { value:"DO", label: "Dominican Republic"},
        { value:"EC", label: "Ecuador"},
        { value:"EG", label: "Egypt"},
        { value:"SV", label: "El Salvador"},
        { value:"GQ", label: "Equatorial Guinea"},
        { value:"ER", label: "Eritrea"},
        { value:"EE", label: "Estonia"},
        { value:"ET", label: "Ethiopia"},
        { value:"FK", label: "Falkland Islands (Malvinas)"},
        { value:"FO", label: "Faroe Islands"},
        { value:"FJ", label: "Fiji"},
        { value:"FI", label: "Finland"},
        { value:"FR", label: "France"},
        { value:"GF", label: "French Guiana"},
        { value:"PF", label: "French Polynesia"},
        { value:"TF", label: "French Southern Territories"},
        { value:"GA", label: "Gabon"},
        { value:"GM", label: "Gambia"},
        { value:"GE", label: "Georgia"},
        { value:"DE", label: "Germany"},
        { value:"GH", label: "Ghana"},
        { value:"GI", label: "Gibraltar"},
        { value:"GR", label: "Greece"},
        { value:"GL", label: "Greenland"},
        { value:"GD", label: "Grenada"},
        { value:"GP", label: "Guadeloupe"},
        { value:"GU", label: "Guam"},
        { value:"GT", label: "Guatemala"},
        { value:"GG", label: "Guernsey"},
        { value:"GN", label: "Guinea"},
        { value:"GW", label: "Guinea-Bissau"},
        { value:"GY", label: "Guyana"},
        { value:"HT", label: "Haiti"},
        { value:"HM", label: "Heard and Mcdonald Islands"},
        { value:"VA", label: "Holy See (Vatican City State)"},
        { value:"HN", label: "Honduras"},
        { value:"HU", label: "Hungary"},
        { value:"IS", label: "Iceland"},
        { value:"IN", label: "India"},
        { value:"ID", label: "Indonesia"},
        { value:"IR", label: "Iran, Islamic Republic of"},
        { value:"IQ", label: "Iraq"},
        { value:"IE", label: "Ireland"},
        { value:"IM", label: "Isle of Man"},
        { value:"IL", label: "Israel"},
        { value:"IT", label: "Italy"},
        { value:"JM", label: "Jamaica"},
        { value:"JP", label: "Japan"},
        { value:"JE", label: "Jersey"},
        { value:"JO", label: "Jordan"},
        { value:"KZ", label: "Kazakhstan"},
        { value:"KE", label: "Kenya"},
        { value:"KI", label: "Kiribati"},
        { value:"KP", label: "Korea (North)"},
        { value:"KR", label: "Korea (South)"},
        { value:"KW", label: "Kuwait"},
        { value:"KG", label: "Kyrgyzstan"},
        { value:"LA", label: "Lao PDR"},
        { value:"LV", label: "Latvia"},
        { value:"LB", label: "Lebanon"},
        { value:"LS", label: "Lesotho"},
        { value:"LR", label: "Liberia"},
        { value:"LY", label: "Libya"},
        { value:"LI", label: "Liechtenstein"},
        { value:"LT", label: "Lithuania"},
        { value:"LU", label: "Luxembourg"},
        { value:"MK", label: "Macedonia, Republic of"},
        { value:"MG", label: "Madagascar"},
        { value:"MW", label: "Malawi"},
        { value:"MY", label: "Malaysia"},
        { value:"MV", label: "Maldives"},
        { value:"ML", label: "Mali"},
        { value:"MT", label: "Malta"},
        { value:"MH", label: "Marshall Islands"},
        { value:"MQ", label: "Martinique"},
        { value:"MR", label: "Mauritania"},
        { value:"MU", label: "Mauritius"},
        { value:"YT", label: "Mayotte"},
        { value:"MX", label: "Mexico"},
        { value:"FM", label: "Micronesia, Federated States of"},
        { value:"MD", label: "Moldova"},
        { value:"MC", label: "Monaco"},
        { value:"MN", label: "Mongolia"},
        { value:"ME", label: "Montenegro"},
        { value:"MS", label: "Montserrat"},
        { value:"MA", label: "Morocco"},
        { value:"MZ", label: "Mozambique"},
        { value:"MM", label: "Myanmar"},
        { value:"NA", label: "Namibia"},
        { value:"NR", label: "Nauru"},
        { value:"NP", label: "Nepal"},
        { value:"NL", label: "Netherlands"},
        { value:"AN", label: "Netherlands Antilles"},
        { value:"NC", label: "New Caledonia"},
        { value:"NZ", label: "New Zealand"},
        { value:"NI", label: "Nicaragua"},
        { value:"NE", label: "Niger"},
        { value:"NG", label: "Nigeria"},
        { value:"NU", label: "Niue"},
        { value:"NF", label: "Norfolk Island"},
        { value:"MP", label: "Northern Mariana Islands"},
        { value:"NO", label: "Norway"},
        { value:"OM", label: "Oman"},
        { value:"PK", label: "Pakistan"},
        { value:"PW", label: "Palau"},
        { value:"PS", label: "Palestinian Territory"},
        { value:"PA", label: "Panama"},
        { value:"PG", label: "Papua New Guinea"},
        { value:"PY", label: "Paraguay"},
        { value:"PE", label: "Peru"},
        { value:"PH", label: "Philippines"},
        { value:"PN", label: "Pitcairn"},
        { value:"PL", label: "Poland"},
        { value:"PT", label: "Portugal"},
        { value:"PR", label: "Puerto Rico"},
        { value:"QA", label: "Qatar"},
        { value:"RE", label: "Réunion"},
        { value:"RO", label: "Romania"},
        { value:"RU", label: "Russian Federation"},
        { value:"RW", label: "Rwanda"},
        { value:"BL", label: "Saint-Barthélemy"},
        { value:"SH", label: "Saint Helena"},
        { value:"KN", label: "Saint Kitts and Nevis"},
        { value:"LC", label: "Saint Lucia"},
        { value:"MF", label: "Saint-Martin (French part)"},
        { value:"PM", label: "Saint Pierre and Miquelon"},
        { value:"VC", label: "Saint Vincent and Grenadines"},
        { value:"WS", label: "Samoa"},
        { value:"SM", label: "San Marino"},
        { value:"ST", label: "Sao Tome and Principe"},
        { value:"SA", label: "Saudi Arabia"},
        { value:"SN", label: "Senegal"},
        { value:"RS", label: "Serbia"},
        { value:"SC", label: "Seychelles"},
        { value:"SL", label: "Sierra Leone"},
        { value:"SG", label: "Singapore"},
        { value:"SK", label: "Slovakia"},
        { value:"SI", label: "Slovenia"},
        { value:"SB", label: "Solomon Islands"},
        { value:"SO", label: "Somalia"},
        { value:"ZA", label: "South Africa"},
        { value:"GS", label: "South Georgia and the South Sandwich Islands"},
        { value:"SS", label: "South Sudan"},
        { value:"ES", label: "Spain"},
        { value:"LK", label: "Sri Lanka"},
        { value:"SD", label: "Sudan"},
        { value:"SR", label: "Suriname"},
        { value:"SJ", label: "Svalbard and Jan Mayen Islands"},
        { value:"SZ", label: "Swaziland"},
        { value:"SE", label: "Sweden"},
        { value:"CH", label: "Switzerland"},
        { value:"SY", label: "Syrian Arab Republic (Syria)"},
        { value:"TW", label: "Taiwan, Republic of China"},
        { value:"TJ", label: "Tajikistan"},
        { value:"TZ", label: "Tanzania, United Republic of"},
        { value:"TH", label: "Thailand"},
        { value:"TL", label: "Timor-Leste"},
        { value:"TG", label: "Togo"},
        { value:"TK", label: "Tokelau"},
        { value:"TO", label: "Tonga"},
        { value:"TT", label: "Trinidad and Tobago"},
        { value:"TN", label: "Tunisia"},
        { value:"TR", label: "Turkey"},
        { value:"TM", label: "Turkmenistan"},
        { value:"TC", label: "Turks and Caicos Islands"},
        { value:"TV", label: "Tuvalu"},
        { value:"UG", label: "Uganda"},
        { value:"UA", label: "Ukraine"},
        { value:"AE", label: "United Arab Emirates"},
        { value:"GB", label: "United Kingdom"},
        { value:"US", label: "United States of America"},
        { value:"UM", label: "US Minor Outlying Islands"},
        { value:"UY", label: "Uruguay"},
        { value:"UZ", label: "Uzbekistan"},
        { value:"VU", label: "Vanuatu"},
        { value:"VE", label: "Venezuela (Bolivarian Republic)"},
        { value:"VN", label: "Viet Nam"},
        { value:"VI", label: "Virgin Islands, US"},
        { value:"WF", label: "Wallis and Futuna Islands"},
        { value:"EH", label: "Western Sahara"},
        { value:"YE", label: "Yemen"},
        { value:"ZM", label: "Zambia"},
        { value:"ZW", label: "Zimbabwe"}        
    ],
    indiaStates : [
         { value: 2, label: "Arunachal Pradesh" },
         { value: 4, label: "Assam" },
         { value: 6, label: "Bihar" },
         { value: 8, label: "Chandigarh" },
         { value: 10, label: "Chhattisgarh" },
         { value: 12, label: "Dadra and Nagar Haveli" },
         { value: 14, label: "Daman and Diu" },
         { value: 16, label: "Delhi" },
         { value: 18, label: "Goa" },
         { value: 20, label: "Gujarat" },
         { value: 22, label: "Haryana" },
         { value: 24, label: "Himachal Pradesh" },
         { value: 26, label: "Jammu and Kashmir" },
         { value: 28, label: "Jharkhand" },
         { value: 30, label: "Karnataka" },
         { value: 32, label: "Kerala" },
         { value: 34, label: "Lakshadweep" },
         { value: 36, label: "Madhya Pradesh" },
         { value: 38, label: "Maharashtra" },
         { value: 40, label: "Manipur" },
         { value: 42, label: "Meghalaya" },
         { value: 44, label: "Mizoram" },
         { value: 46, label: "Nagaland" },
         { value: 48, label: "Odisha" },
         { value: 50, label: "Puducherry" },
         { value: 52, label: "Punjab" },
         { value: 54, label: "Rajasthan" },
         { value: 56, label: "Sikkim" },
         { value: 58, label: "Tamil Nadu" },
         { value: 60, label: "Telangana" },
         { value: 62, label: "Tripura" },
         { value: 64, label: "Uttar Pradesh" },
         { value: 66, label: "Uttarakhand" },
         { value: 68, label: "West Bengal" }
     ],
     tamilnaduDistricts :[
        { value: 0, label: "--Select--" },
        { value: 1, label: "Ariyalur" },
        { value: 2, label: "Chennai" },  
        { value: 3, label: "Coimbatore" },  
        { value: 4, label: "Cuddalore" },  
        { value: 5, label: "Dharmapuri" },  
        { value: 6, label: "Dindigul" },  
        { value: 7, label: "Erode" }, 
        { value: 8, label: "Kanchipuram" },  
        { value: 9, label: "Kanyakumari" },  
        { value: 10, label: "Karur" },  
        { value: 11, label: "Krishnagiri" },  
        { value: 12, label: "Madurai" },  
        { value: 13, label: "Nagapattinam" },  
        { value: 14, label: "Namakkal" },  
        { value: 15, label: "Nilgiris" },  
        { value: 16, label: "Perambalur" },
        { value: 17, label: "Pudukkottai" },
        { value: 18, label: "Ramanathapuram" },
        { value: 19, label: "Salem" },
        { value: 20, label: "Sivagangai" },
        { value: 21, label: "Thanjavur" },
        { value: 22, label: "Theni" },
        { value: 23, label: "Thoothukudi" },
        { value: 24, label: "Tiruchirappalli" },
        { value: 25, label: "Tirunelveli" },
        { value: 26, label: "Tiruppur" },
        { value: 27, label: "Tiruvallur" },
        { value: 28, label: "Tiruvannamalai" },
        { value: 29, label: "Tiruvarur" },
        { value: 30, label: "Vellore" },
        { value: 31, label: "Viluppuram" },
        { value: 32, label: "Virudunagar" }
       ],
}