export default {

    mStatus_NM:[{value:'NM',label:"Never Married"}],
    dropdownDefault:"--Select--",
    
    regilionValues :[
        { value: 1, label: "Hindu" },
        { value: 2, label: "Buddhist" },      
        { value: 3, label: "Christian" },
        { value: 4, label: "Muslim - Shia" },
        { value: 5, label: "Muslim - Sunni" },
        { value: 6, label: "Muslim - Others" },
        { value: 7, label: "Sikh" },
        { value: 8, label: "Jain - Digambar" },
        { value: 9, label: "Jain - Shwetambar" },
        { value: 10, label: "Jain - Others" },
        { value: 11, label: "Parsi" },
        { value: 12, label: "Inter-Religion" }
     ],
     gothramValues :[
        { value: "1", label: "Anuradha / Anusham / Anizham" },
        { value: "2", label: "Ardra / Thiruvathira" },
        { value: "3", label: "Ashlesha / Ayilyam" },
        { value: "4", label: "Ashwini / Ashwathi" },
        { value: "5", label: "Bharani" },
        { value: "6", label: "Chitra / Chitha" },
        { value: "7", label: "Dhanista / Avittam" },
        { value: "8", label: "Hastha / Atham" },
        { value: "9", label: "Jyesta / Kettai" },
        { value: "10", label: "Kettai" },
        { value: "11", label: "Krithika / Karthika" },
        { value: "12", label: "Makha / Magam" },
        { value: "13", label: "Moolam / Moola" },
        { value: "14", label: "Mrigasira / Makayiram" },
        { value: "15", label: "Poorvabadrapada / Puratathi" },
        { value: "16", label: "Poorvapalguni / Puram / Pubbhe" },
        { value: "17", label: "Poorvashada / Pooradam" },
        { value: "18", label: "Punarvasu / Punarpusam" },
        { value: "19", label: "Pushya / Poosam / Pooyam" },
        { value: "20", label: "Revathi" },
        { value: "21", label: "Rohini" },
        { value: "22", label: "Shatataraka / Sadayam / Satabishek" },
        { value: "23", label: "Shravan / Thiruvonam" },
        { value: "24", label: "Swati / Choth" },
        { value: "25", label: "Uthram" },
        { value: "26", label: "Uttarabadrapada / Uthratadhi" },
        { value: "27", label: "Uttarapalguni / UthramUttarashada / Uthradam" },
        { value: "28", label: "Vishaka / Vishakam" },
     ],
     casteValues :[
        { value: "VAN", label: "Vanniyar" },
        { value: "MUL", label: "Mudaliyar" }  
     ],
     maritalStatusValues :[
        { value: "NM", label: "Never Married" },
        { value: "WD", label: "Widowed" },
        { value: "DD", label: "Divorced" },
        { value: "AD", label: "Awaiting Divorce" }
     ],
     educationValues :[
      { value: "BE", label: "Bachelor of Engineering" },
      { value: "BT", label: "Bachelor of Technology" },
      { value: "DP", label: "Diplamo" },
      { value: "ME", label: "Masters Engineering" },
      { value: "HS", label: "Higher Secondary" }      
      ],
      employmentValues :[
         { value: "G", label: "Government" },
         { value: "P", label: "Private" },
         { value: "B", label: "Business" },
         { value: "D", label: "Defence" },
         { value: "S", label: "Self Employed" },
         { value: "N", label: "Not Working" }      
      ],      
     dhoshamValues :[
      { value: "-", label: "--Nil--" },
      { value: "C", label: "Chevvai dosham" },
      { value: "N", label: "Naga dosham Kala" },
      { value: "R", label: "Rahu dosham" },
      { value: "K", label: "Kethu dosham" },
      { value: "A", label: "Kalathra dosham" },
      ],
     countries :[
         { value: "IND", label: "India" },
         { value: "USA", label: "United States of America" },
         { value: "GBR", label: "United Kingdom" } 
     ],
     indiaStates : [
         { value: "AR", label: "Arunachal Pradesh" },
         { value: "AS", label: "Assam" },
         { value: "BR", label: "Bihar" },
         { value: "CH", label: "Chandigarh" },
         { value: "CG", label: "Chhattisgarh" },
         { value: "DN", label: "Dadra and Nagar Haveli" },
         { value: "DD", label: "Daman and Diu" },
         { value: "DL", label: "Delhi" },
         { value: "GA", label: "Goa" },
         { value: "GJ", label: "Gujarat" },
         { value: "HR", label: "Haryana" },
         { value: "HP", label: "Himachal Pradesh" },
         { value: "JK", label: "Jammu and Kashmir" },
         { value: "JH", label: "Jharkhand" },
         { value: "KA", label: "Karnataka" },
         { value: "KL", label: "Kerala" },
         { value: "LD", label: "Lakshadweep" },
         { value: "MP", label: "Madhya Pradesh" },
         { value: "MH", label: "Maharashtra" },
         { value: "MN", label: "Manipur" },
         { value: "ML", label: "Meghalaya" },
         { value: "MZ", label: "Mizoram" },
         { value: "NL", label: "Nagaland" },
         { value: "OD", label: "Odisha" },
         { value: "PY", label: "Puducherry" },
         { value: "PB", label: "Punjab" },
         { value: "RJ", label: "Rajasthan" },
         { value: "SK", label: "Sikkim" },
         { value: "TN", label: "Tamil Nadu" },
         { value: "TS", label: "Telangana" },
         { value: "TR", label: "Tripura" },
         { value: "UP", label: "Uttar Pradesh" },
         { value: "UK", label: "Uttarakhand" },
         { value: "WB", label: "West Bengal" }
     ],
     tamilnaduDistrict :[
         { value: "AR", label: "Ariyalur" },
         { value: "CH", label: "Chennai" },
         { value: "CO", label: "Coimbatore"},  
         { value: "CU", label: "Cuddalore" },
         { value: "DH", label: "Dharmapuri" },
         { value: "DI", label: "Dindigul" },
         { value: "ER", label: "Erode" },
         { value: "KM", label: "Kanchipuram" },
         { value: "KK", label: "Kanyakumari" },
         { value: "KR", label: "Karur" },
         { value: "KG", label: "Krishnagiri" },
         { value: "MA", label: "Madurai" },
         { value: "NA", label: "Nagapattinam" },
         { value: "NL", label: "Namakkal" },
         { value: "NI", label: "Nilgiris" },
         { value: "PE", label: "Perambalur" },
         { value: "PU", label: "Pudukkottai" },
         { value: "RA", label: "Ramanathapuram" },
         { value: "SM", label: "Salem" },
         { value: "SI", label: "Sivagangai" },
         { value: "TJ", label: "Thanjavur" },
         { value: "TH", label: "Theni" },
         { value: "TK", label: "Thoothukudi" },
         { value: "TI", label: "Tiruchirappalli" },
         { value: "TN", label: "Tirunelveli" },
         { value: "TP", label: "Tiruppur" },
         { value: "TV", label: "Tiruvallur" },
         { value: "TM", label: "Tiruvannamalai" },
         { value: "TR", label: "Tiruvarur" },
         { value: "VR", label: "Vellore" },
         { value: "VP", label: "Viluppuram" },
         { value: "VN", label: "Virudunagar" }
      ],

     customSelectStyles : {     
        control: () => ({
          maxHeight:30,
          minHeight:30
        })     
      }
}