export default {

    mStatus_NM:[{value:'NM',label:"Never Married"}],
    dropdownDefault:"--Select--",

    motherToungeValues :[
      { value: 12, label: "Bengali" },
      { value: 2, label: "Gujarati" },      
      { value: 3, label: "Hindi" },
      { value: 4, label: "Kannada" },
      { value: 5, label: "Konkani" },
      { value: 6, label: "Malayalam" },
      { value: 7, label: "Marathi" },
      { value: 8, label: "Marwari" },
      { value: 9, label: "Oriya" },
      { value: 10, label: "Punjabi" },
      { value: 11, label: "Sindhi" },
      { value: 1, label: "Tamil" },
      { value: 13, label: "Telugu" },
      { value: 14, label: "Urdu" }
   ],     
     maritalStatusValues :[
        { value: "NM", label: "Never Married" },
        { value: "WD", label: "Widowed" },
        { value: "DD", label: "Divorced" },
        { value: "AD", label: "Awaiting Divorce" }
     ],
     educationValues :[
         { value:"AE", label: "Aeronautical Engineering"},
         { value:"AD", label: "Aviation Degree"},
         { value:"BA", label: "B.A"},
         { value:"BAMS", label: "B.A.M.S"},
         { value:"BARCH", label: "B.Arch"},
         { value:"BCOM", label: "B.Com"},
         { value:"BED", label: "B.Ed"},
         { value:"BL", label: "B.L"},
         { value:"BMM", label: "B.M.M"},
         { value:"BPHIL", label: "B.Phil"},
         { value:"BPLAN", label: "B.Plan"},
         { value:"BSE", label: "B.S (Engineering)"},
         { value:"BSW", label: "B.S.W"},
         { value:"BSCIT", label: "B.SC IT/Computer Science"},
         { value:"BSCN", label: "B.Sc Nursing"},
         { value:"BSC", label: "B.Sc."},
         { value:"BTECH", label: "B.Tech"},
         { value:"BBA", label: "BBA"},
         { value:"BCA", label: "BCA"},
         { value:"BDS", label: "BDS"},
         { value:"BE", label: "BE"},
         { value:"BFA", label: "BFA"},
         { value:"BFM", label: "BFM - Bachelor of Financial Management"},
         { value:"BFT", label: "BFT"},
         { value:"BGL", label: "BGL"},
         { value:"BHA", label: "BHA - Bachelor of Hospital Administration"},
         { value:"BHM", label: "BHM - Bachelor of Hospital Management"},
         { value:"BHMT", label: "BHM - Bachelor of Hotel Management"},
         { value:"BHMS", label: "BHMS"},
         { value:"BLIS", label: "BLIS"},
         { value:"BPT", label: "BPT"},
         { value:"BPHARM", label: "BPharm"},
         { value:"BUMS", label: "BUMS"},
         { value:"BVSC", label: "BVSc"},
         { value:"CA", label: "CA"},
         { value:"CFA", label: "CFA - Chartered Financial Analyst"},
         { value:"CS", label: "CS"},
         { value:"DTED", label: "D.Ted"},
         { value:"DIPLOMA", label: "Diploma"},
         { value:"HSC", label: "Higher Secondary School"},
         { value:"IAS", label: "IAS"},
         { value:"ICWA", label: "ICWA"},
         { value:"IES", label: "IES"},
         { value:"IFS", label: "IFS"},
         { value:"LLB", label: "LL.B"},
         { value:"LLM", label: "LL.M"},
         { value:"MA", label: "M.A"},
         { value:"MARCH", label: "M.Arch"},
         { value:"MED", label: "M.Ed."},
         { value:"ML", label: "M.L"},
         { value:"MPHARM", label: "M.Pharm"},
         { value:"MPHIL", label: "M.Phil."},
         { value:"MSE", label: "M.S.(Engg)"},
         { value:"MSCIT", label: "M.Sc IT / Computer Science"},
         { value:"MSC", label: "M.Sc. - Master of Science"},
         { value:"MTECH", label: "M.Tech"},
         { value:"MBA", label: "MBA"},
         { value:"MBBS", label: "MBBS"},
         { value:"MCA", label: "MCA"},
         { value:"MCOM", label: "MCom"},
         { value:"MD", label: "MD"},
         { value:"MDS", label: "MDS"},
         { value:"ME", label: "ME"},
         { value:"MFA", label: "MFA"},
         { value:"MFM", label: "MFM - Master of Financial Management"},
         { value:"MHM", label: "MHM - Master of Hotel Management"},
         { value:"MHRM", label: "MHRM - Master of Human Resource Management"},
         { value:"MPT", label: "MPT"},
         { value:"MSM", label: "MS-Medical"},
         { value:"MSW", label: "MSW"},
         { value:"MVSC", label: "MVSc"},
         { value:"PGDCA", label: "PGDCA"},
         { value:"PGDM", label: "PGDM"},
         { value:"PHD", label: "Ph.d"},
         { value:"PTECH", label: "Polytechnic"}     
      ],
      employmentValues :[
         { value: "G", label: "Government" },
         { value: "P", label: "Private" },
         { value: "B", label: "Business" },
         { value: "D", label: "Defence" },
         { value: "S", label: "Self Employed" },
         { value: "N", label: "Not Working" }      
      ],   
      incomeValues :[
         { value: "1-50000", label: "Less than 25,000" },
         { value: "50000-100000", label: "50,000 - 100,000" }, 
         { value: "100000-200000", label: "100,000 - 200,000" },      
         { value: "200000-300000", label: "200,000 - 300,000" },      
         { value: "200000", label: "2L and above" }, 
         { value: "300000-400000", label: "300,000 - 400,000" },    
         { value: "300000", label: "3L and above" },  
         { value: "400000-500000", label: "400,000 - 500,000" },
         { value: "400000", label: "4L and above" },      
         { value: "500000-600000", label: "500,000 - 600,000" },   
         { value: "500000", label: "5L and above" },   
         { value: "600000-700000", label: "600,000 - 700,000" }, 
         { value: "600000", label: "6L and above" },   
         { value: "700000-800000", label: "700,000 - 800,000" },      
         { value: "700000", label: "7L and above" },
         { value: "800000-900000", label: "800,000 - 900,000" },      
         { value: "800000", label: "8L and above" },
         { value: "900000-1000000", label: "900,000 - 10,00,000" },
         { value: "900000", label: "9L and above" },
         { value: "1000000", label: "10L and above" },
         { value: "2000000", label: "20L and above" },
      ],     
     
}