export default {

    mStatus_NM:[{value:'NM',label:"Never Married"}],
    mtongue_DF:[{value:250,label:"Tamil"}],
    mtongue_SEL_DF:{value:250,label:"Tamil"},
    dropdownDefault:"--Select--",

    motherToungeValues :[
      { value: 12, label: "Bengali" },
      { value: 2, label: "Gujarati" },      
      { value: 3, label: "Hindi" },
      { value: 4, label: "Kannada" },
      { value: 5, label: "Konkani" },
      { value: 6, label: "Malayalam" },
      { value: 7, label: "Marathi" },
      { value: 8, label: "Marwari" },
      { value: 9, label: "Oriya" },
      { value: 10, label: "Punjabi" },
      { value: 11, label: "Sindhi" },
      { value: 1, label: "Tamil" },
      { value: 13, label: "Telugu" },
      { value: 14, label: "Urdu" }
   ],     
     maritalStatusValues :[
        { value: "NM", label: "Never Married" },
        { value: "WD", label: "Widowed" },
        { value: "DD", label: "Divorced" },
        { value: "AD", label: "Awaiting Divorce" }
     ],
     educationValues :[
         { value:"AE", label: "Aeronautical Engineering"},
         { value:"AD", label: "Aviation Degree"},
         { value:"BA", label: "B.A"},
         { value:"BAMS", label: "B.A.M.S"},
         { value:"BARCH", label: "B.Arch"},
         { value:"BCOM", label: "B.Com"},
         { value:"BED", label: "B.Ed"},
         { value:"BL", label: "B.L"},
         { value:"BMM", label: "B.M.M"},
         { value:"BPHIL", label: "B.Phil"},
         { value:"BPLAN", label: "B.Plan"},
         { value:"BSE", label: "B.S (Engineering)"},
         { value:"BSW", label: "B.S.W"},
         { value:"BSCIT", label: "B.SC IT/Computer Science"},
         { value:"BSCN", label: "B.Sc Nursing"},
         { value:"BSC", label: "B.Sc."},
         { value:"BTECH", label: "B.Tech"},
         { value:"BBA", label: "BBA"},
         { value:"BCA", label: "BCA"},
         { value:"BDS", label: "BDS"},
         { value:"BE", label: "BE"},
         { value:"BFA", label: "BFA"},
         { value:"BFM", label: "BFM - Bachelor of Financial Management"},
         { value:"BFT", label: "BFT"},
         { value:"BGL", label: "BGL"},
         { value:"BHA", label: "BHA - Bachelor of Hospital Administration"},
         { value:"BHM", label: "BHM - Bachelor of Hospital Management"},
         { value:"BHMT", label: "BHM - Bachelor of Hotel Management"},
         { value:"BHMS", label: "BHMS"},
         { value:"BLIS", label: "BLIS"},
         { value:"BPT", label: "BPT"},
         { value:"BPHARM", label: "BPharm"},
         { value:"BUMS", label: "BUMS"},
         { value:"BVSC", label: "BVSc"},
         { value:"CA", label: "CA"},
         { value:"CFA", label: "CFA - Chartered Financial Analyst"},
         { value:"CS", label: "CS"},
         { value:"DTED", label: "D.Ted"},
         { value:"DIPLOMA", label: "Diploma"},
         { value:"HSC", label: "Higher Secondary School"},
         { value:"IAS", label: "IAS"},
         { value:"ICWA", label: "ICWA"},
         { value:"IES", label: "IES"},
         { value:"IFS", label: "IFS"},
         { value:"LLB", label: "LL.B"},
         { value:"LLM", label: "LL.M"},
         { value:"MA", label: "M.A"},
         { value:"MARCH", label: "M.Arch"},
         { value:"MED", label: "M.Ed."},
         { value:"ML", label: "M.L"},
         { value:"MPHARM", label: "M.Pharm"},
         { value:"MPHIL", label: "M.Phil."},
         { value:"MSE", label: "M.S.(Engg)"},
         { value:"MSCIT", label: "M.Sc IT / Computer Science"},
         { value:"MSC", label: "M.Sc. - Master of Science"},
         { value:"MTECH", label: "M.Tech"},
         { value:"MBA", label: "MBA"},
         { value:"MBBS", label: "MBBS"},
         { value:"MCA", label: "MCA"},
         { value:"MCOM", label: "MCom"},
         { value:"MD", label: "MD"},
         { value:"MDS", label: "MDS"},
         { value:"ME", label: "ME"},
         { value:"MFA", label: "MFA"},
         { value:"MFM", label: "MFM - Master of Financial Management"},
         { value:"MHM", label: "MHM - Master of Hotel Management"},
         { value:"MHRM", label: "MHRM - Master of Human Resource Management"},
         { value:"MPT", label: "MPT"},
         { value:"MSM", label: "MS-Medical"},
         { value:"MSW", label: "MSW"},
         { value:"MVSC", label: "MVSc"},
         { value:"PGDCA", label: "PGDCA"},
         { value:"PGDM", label: "PGDM"},
         { value:"PHD", label: "Ph.d"},
         { value:"PTECH", label: "Polytechnic"}     
      ],
      employmentValues :[
         { value: "G", label: "Government" },
         { value: "P", label: "Private" },
         { value: "B", label: "Business" },
         { value: "D", label: "Defence" },
         { value: "S", label: "Self Employed" },
         { value: "N", label: "Not Working" }      
      ],   
      occupationValues :[
         {
            label: "--ADMIN--",
            options: [
              { value:10, label: "Administrative Professional" },
              { value:15, label: "Clerk"},
              { value:20, label: "Executive"},
              { value:25, label: "Human Resource Professional - HR"},
              { value:30, label: "Manager"},
              { value:35, label: "Officer"},
              { value:40, label: "Supervisor"}
            ]
          },     
          {
            label: "--AGRICULTURE--",
            options: [
               { value:50, label: "Agriculture & Farming Professional"}
            ]
          },
          {
            label: "--AIRLINE--",
            options: [
               { value:60, label: "Pilot"},
               { value:65, label: "Air Hostes"},
               { value:70, label: "Airline Professional"},
               { value:75, label: "Aiport Services"},
            ]
          },
          {
            label: "--ARCHITECT--",
            options: [
               { value:85, label: "Architect"},
               { value:90, label: "Interior Designer"},
            ]
          },
          {
            label: "--BANKING & FINANCE--",
            options: [
               { value:100, label: "Accounts Finance Professional"},
               { value:105, label: "Aditor"},
               { value:110, label: "Banking Service Professional"},
               { value:115, label: "Charted Accountant"},
               { value:120, label: "Company Secretary"},
               { value:125, label: "Financial Accountant"},
               { value:130, label: "Financial Analyst/Planning"},
            ]
          },
          {
            label: "--BEAUTY & FASHION--",
            options: [
               { value:140, label: "Beautician"},
               { value:145, label: "Fashion Designer"},
            ]
          },
          {
            label: "--CIVIL SERVICES--",
            options: [
               { value:155, label: "Civil Services -IAS"},
               { value:160, label: "Civil Services -IES"},
               { value:165, label: "Civil Services -IFS"},
               { value:170, label: "Civil Services -IPS"},
               { value:175, label: "Civil Services -IRS"},
            ]
          },       
          {
            label: "--DEFENCE--",
            options: [
               { value:185, label: "Army"},
               { value:190, label: "Navy"},
               { value:195, label: "Airforce"},
            ]
          },
          {
            label: "--EDUCATION--",
            options: [
               { value:205, label: "Education Professional"},
               { value:210, label: "Professor/Lecturer"},
               { value:215, label: "Teaching/Academician"},
            ]
          },
          {
            label: "--HOSPITALITY--",
            options: [
               { value:225, label: "Hotel/Hospitality Professional"},
            ]
          },
          {
            label: "--IT & ENGINEERING--",
            options: [
               { value:235, label: "Designer"},
               { value:240, label: "Engineer - Non IT"},
               { value:245, label: "Hardware Professional"},
               { value:250, label: "Software Professional"},
            ]
          },
          {
            label: "--LEGAL--",
            options: [
               { value:260, label: "Lawyer & Legal Professinal"},
            ]
          },
          {
            label: "--MEDICAL--",
            options: [
               { value:270, label: "Doctor"},
               { value:275, label: "Healthcare Professional"},
               { value:280, label: "Nurse"},
               { value:285, label: "Paramedical Professional"},
            ]
          },
          {
            label: "--MARKETING & SALES--",
            options: [
               { value:295, label: "Marketing Professional"},
               { value:300, label: "Sales Professional"},
            ]
          },
          {
            label: "--MEDIA & ENTERTAINMENT--",
            options: [
               { value:310, label: "Advertising/PR Professional"},
               { value:315, label: "Designer"},
               { value:320, label: "Entertainment Professional"},
               { value:325, label: "Journalist"},
               { value:330, label: "Media Professional"},
            ]
          },
          {
            label: "--MERCHANT NAVY--",
            options: [
               { value:340, label: "Mariner/Merchant Navy"},
            ]
          },
          {
            label: "--SCIENTIST--",
            options: [
               { value:350, label: "Scientist/Researcher"},
            ]
          },
          {
            label: "--TOP MANAGEMENT--",
            options: [
               { value:360, label: "CEO/President/Chairman/Director"},
            ]
          },
          {
            label: "--OTHER PROFESSIONS--",
            options: [
               { value:370, label: "Arts/Craftsman"},
               { value:375, label: "Business Owner/Entrepreneur"},
               { value:380, label: "Consultant"},
               { value:385, label: "Customer Care Professional"},
               { value:390, label: "Labour"},
               { value:395, label: "Other"},
               { value:400, label: "Social Worker"},
               { value:405, label: "Sportsman"},
               { value:410, label: "Technician"} 
            ]
          },         
      ], 
      occupationValuesAll :[
         { value:10, label: "Administrative Professional"},
         { value:15, label: "Clerk"},
         { value:20, label: "Executive"},
         { value:25, label: "Human Resource Professional - HR"},
         { value:30, label: "Manager"},
         { value:35, label: "Officer"},
         { value:40, label: "Supervisor"},
         { value:50, label: "Agriculture & Farming Professional"},
         { value:60, label: "Pilot"},
         { value:65, label: "Air Hostes"},
         { value:70, label: "Airline Professional"},
         { value:75, label: "Aiport Services"},
         { value:85, label: "Architect"},
         { value:90, label: "Interior Designer"},
         { value:100, label: "Accounts Finance Professional"},
         { value:105, label: "Aditor"},
         { value:110, label: "Banking Service Professional"},
         { value:115, label: "Charted Accountant"},
         { value:120, label: "Company Secretary"},
         { value:125, label: "Financial Accountant"},
         { value:130, label: "Financial Analyst/Planning"},
         { value:140, label: "Beautician"},
         { value:145, label: "Fashion Designer"},
         { value:155, label: "Civil Services -IAS"},
         { value:160, label: "Civil Services -IES"},
         { value:165, label: "Civil Services -IFS"},
         { value:170, label: "Civil Services -IPS"},
         { value:175, label: "Civil Services -IRS"},
         { value:185, label: "Army"},
         { value:190, label: "Navy"},
         { value:195, label: "Airforce"},
         { value:205, label: "Education Professional"},
         { value:210, label: "Professor/Lecturer"},
         { value:215, label: "Teaching/Academician"},
         { value:225, label: "Hotel/Hospitality Professional"},
         { value:235, label: "Designer"},
         { value:240, label: "Engineer - Non IT"},
         { value:245, label: "Hardware Professional"},
         { value:250, label: "Software Professional"},
         { value:260, label: "Lawyer & Legal Professinal"},
         { value:270, label: "Doctor"},
         { value:275, label: "Healthcare Professional"},
         { value:280, label: "Nurse"},
         { value:285, label: "Paramedical Professional"},
         { value:295, label: "Marketing Professional"},
         { value:300, label: "Sales Professional"},
         { value:310, label: "Advertising/PR Professional"},
         { value:315, label: "Designer"},
         { value:320, label: "Entertainment Professional"},
         { value:325, label: "Journalist"},
         { value:330, label: "Media Professional"},
         { value:340, label: "Mariner/Merchant Navy"},
         { value:350, label: "Scientist/Researcher"},
         { value:360, label: "CEO/President/Chairman/Director"},
         { value:370, label: "Arts/Craftsman"},
         { value:375, label: "Business Owner/Entrepreneur"},
         { value:380, label: "Consultant"},
         { value:385, label: "Customer Care Professional"},
         { value:390, label: "Labour"},
         { value:395, label: "Other"},
         { value:400, label: "Social Worker"},
         { value:405, label: "Sportsman"},
         { value:410, label: "Technician"} 
      ], 
      incomeValues :[
         { value:10, label: "Less than 25,000" },
         { value:20, label: "50,000 - 100,000" }, 
         { value:30, label: "100,000 - 200,000" },      
         { value:40, label: "200,000 - 300,000" },      
         { value:50, label: "2L and above" }, 
         { value:60, label: "300,000 - 400,000" },    
         { value:70, label: "3L and above" },  
         { value:80, label: "400,000 - 500,000" },
         { value:90, label: "4L and above" },      
         { value:100, label: "500,000 - 600,000" },   
         { value:110, label: "5L and above" },   
         { value:120, label: "600,000 - 700,000" }, 
         { value:130, label: "6L and above" },   
         { value:140, label: "700,000 - 800,000" },      
         { value:150, label: "7L and above" },
         { value:160, label: "800,000 - 900,000" },      
         { value:170, label: "8L and above" },
         { value:180, label: "900,000 - 10,00,000" },
         { value:190, label: "9L and above" },
         { value:200, label: "10L and above" },
         { value:210, label: "20L and above" },
      ],
      motherTongueValues :[
         { value:5, label: "Any"},
         { value:10, label: "Angika"},         
         { value:15, label: "Arunachali"},
         { value:20, label: "Assamese"},
         { value:25, label: "Awadhi"},
         { value:30, label: "Badaga"},
         { value:35, label: "Bengali"},
         { value:40, label: "Bhojpuri"},
         { value:45, label: "Bihari"},
         { value:50, label: "Brij"},
         { value:55, label: "Chatisgarhi"},
         { value:60, label: "Dogri"},
         { value:65, label: "English"},
         { value:70, label: "French"},
         { value:75, label: "Garhwali"},
         { value:80, label: "Garo"},
         { value:85, label: "Gujarati"},
         { value:90, label: "Haryanvi"},
         { value:95, label: "Himachali"},
         { value:100, label: "Hindi"},
         { value:105, label: "Kanauji"},
         { value:110, label: "Kannada"},
         { value:115, label: "Kashmiri"},
         { value:120, label: "Khandesi"},
         { value:125, label: "Khasi"},
         { value:130, label: "Konkani"},
         { value:135, label: "Koshali"},
         { value:140, label: "Kumaoni"},
         { value:145, label: "Kutchi"},
         { value:150, label: "Ladacki"},
         { value:155, label: "Lepcha"},
         { value:160, label: "Magahi"},
         { value:165, label: "Maithili"},
         { value:170, label: "Malayalam"},
         { value:175, label: "Manipuri"},
         { value:180, label: "Marathi"},
         { value:185, label: "Marwari"},
         { value:190, label: "Miji"},
         { value:195, label: "Mizo"},
         { value:200, label: "Monpa"},
         { value:205, label: "Nepali"},
         { value:210, label: "Nicobarese"},
         { value:215, label: "Oriya"},
         { value:220, label: "Punjabi"},
         { value:225, label: "Rajasthani"},
         { value:230, label: "Sanskrit"},
         { value:235, label: "Santhali"},
         { value:240, label: "Sindhi"},
         { value:245, label: "Sourashtra"},
         { value:250, label: "Tamil"},
         { value:255, label: "Telugu"},
         { value:260, label: "Tripuri"},
         { value:265, label: "Tulu"},
         { value:270, label: "Urdu"}     
      ],      
      motherTongueSValues :[
         { value:10, label: "Angika"},         
         { value:15, label: "Arunachali"},
         { value:20, label: "Assamese"},
         { value:25, label: "Awadhi"},
         { value:30, label: "Badaga"},
         { value:35, label: "Bengali"},
         { value:40, label: "Bhojpuri"},
         { value:45, label: "Bihari"},
         { value:50, label: "Brij"},
         { value:55, label: "Chatisgarhi"},
         { value:60, label: "Dogri"},
         { value:65, label: "English"},
         { value:70, label: "French"},
         { value:75, label: "Garhwali"},
         { value:80, label: "Garo"},
         { value:85, label: "Gujarati"},
         { value:90, label: "Haryanvi"},
         { value:95, label: "Himachali"},
         { value:100, label: "Hindi"},
         { value:105, label: "Kanauji"},
         { value:110, label: "Kannada"},
         { value:115, label: "Kashmiri"},
         { value:120, label: "Khandesi"},
         { value:125, label: "Khasi"},
         { value:130, label: "Konkani"},
         { value:135, label: "Koshali"},
         { value:140, label: "Kumaoni"},
         { value:145, label: "Kutchi"},
         { value:150, label: "Ladacki"},
         { value:155, label: "Lepcha"},
         { value:160, label: "Magahi"},
         { value:165, label: "Maithili"},
         { value:170, label: "Malayalam"},
         { value:175, label: "Manipuri"},
         { value:180, label: "Marathi"},
         { value:185, label: "Marwari"},
         { value:190, label: "Miji"},
         { value:195, label: "Mizo"},
         { value:200, label: "Monpa"},
         { value:205, label: "Nepali"},
         { value:210, label: "Nicobarese"},
         { value:215, label: "Oriya"},
         { value:220, label: "Punjabi"},
         { value:225, label: "Rajasthani"},
         { value:230, label: "Sanskrit"},
         { value:235, label: "Santhali"},
         { value:240, label: "Sindhi"},
         { value:245, label: "Sourashtra"},
         { value:250, label: "Tamil"},
         { value:255, label: "Telugu"},
         { value:260, label: "Tripuri"},
         { value:265, label: "Tulu"},
         { value:270, label: "Urdu"}     
      ],      
     
}