export default {

    regilionValues :[
        { value:0, label:"--Select--" },
        { value:1, label:"Hindu" },
        { value:2, label:"Buddhist" },      
        { value:3, label:"Christian" },
        { value:4, label:"Muslim - Shia" },
        { value:5, label:"Muslim - Sunni" },
        { value:6, label:"Muslim - Others" },
        { value:7, label:"Sikh" },
        { value:8, label:"Jain - Digambar" },
        { value:9, label:"Jain - Shwetambar" },
        { value:10, label:"Jain - Others" },
        { value:11, label:"Parsi" },
        { value:12, label:"Inter-Religion" }
     ],
     gothramValues :[
        { value:0, label:"--Select--" },
        { value: "1", label: "Anuradha / Anusham / Anizham" },
        { value: "2", label: "Ardra / Thiruvathira" },
        { value: "3", label: "Ashlesha / Ayilyam" },
        { value: "4", label: "Ashwini / Ashwathi" },
        { value: "5", label: "Bharani" },
        { value: "6", label: "Chitra / Chitha" },
        { value: "7", label: "Dhanista / Avittam" },
        { value: "8", label: "Hastha / Atham" },
        { value: "9", label: "Jyesta / Kettai" },
        { value: "10", label: "Kettai" },
        { value: "11", label: "Krithika / Karthika" },
        { value: "12", label: "Makha / Magam" },
        { value: "13", label: "Moolam / Moola" },
        { value: "14", label: "Mrigasira / Makayiram" },
        { value: "15", label: "Poorvabadrapada / Puratathi" },
        { value: "16", label: "Poorvapalguni / Puram / Pubbhe" },
        { value: "17", label: "Poorvashada / Pooradam" },
        { value: "18", label: "Punarvasu / Punarpusam" },
        { value: "19", label: "Pushya / Poosam / Pooyam" },
        { value: "20", label: "Revathi" },
        { value: "21", label: "Rohini" },
        { value: "22", label: "Shatataraka / Sadayam / Satabishek" },
        { value: "23", label: "Shravan / Thiruvonam" },
        { value: "24", label: "Swati / Choth" },
        { value: "25", label: "Uthram" },
        { value: "26", label: "Uttarabadrapada / Uthratadhi" },
        { value: "27", label: "Uttarapalguni / UthramUttarashada / Uthradam" },
        { value: "28", label: "Vishaka / Vishakam" },
     ],
     casteValues :[
        { value: "VAN", label: "Vanniyar" },
        { value: "MUL", label: "Mudaliyar" }  
     ],    
     muslimCasteValues :[
        { value: 0, label: "--Select--" },
        { value: 2002, label: "Ansari" },
        { value: 2004, label: "Arain" },  
        { value: 2006, label: "Awan" },  
        { value: 2008, label: "Bohra" },  
        { value: 2009, label: "Dekkani" },  
        { value: 2010, label: "Dudekula" },  
        { value: 2012, label: "Hanafi" }, 
        { value: 2014, label: "Jat" },  
        { value: 2016, label: "Khoja" },  
        { value: 2018, label: "Lebbai" },  
        { value: 2020, label: "Malik" },  
        { value: 2022, label: "Mapila" },  
        { value: 2024, label: "Maraicar" },  
        { value: 2026, label: "Memon" },  
        { value: 2028, label: "Mughal" },  
        { value: 2030, label: "Pathan" },
        { value: 2032, label: "Qureshi" },
        { value: 2034, label: "Rajput" },
        { value: 2036, label: "Rawther" },
        { value: 2038, label: "Shafi" },
        { value: 2040, label: "Sheikh" },
        { value: 2042, label: "Siddiqui" },
        { value: 2044, label: "Syed" },
        { value: 2046, label: "Others" }
     ],
     hinduCasteValues :[
         { value:0, label: "--Select--"},
         { value:2, label: "Aaru Nattu Vellala"},
         { value:4, label: "Achirapakkam Chettiar"},
         { value:6, label: "Ad Dharmi"},
         { value:8, label: "Adi Andhra"},
         { value:10, label: "Adi Dravidar"},
         { value:12, label: "Adi Karnataka"},
         { value:14, label: "Agamudayar - Arcot - Thuluva Vellala"},
         { value:16, label: "Agaram Vellan Chettiar"},
         { value:18, label: "Agarwal"},
         { value:20, label: "Agnikula Kshatriya"},
         { value:22, label: "Agrahari"},
         { value:24, label: "Agri"},
         { value:26, label: "Aguri - Ugra Kshatriya"},
         { value:28, label: "Aheriya"},
         { value:30, label: "Ahir Shimpi"},
         { value:32, label: "Ahirwar"},
         { value:34, label: "Ahom"},
         { value:36, label: "Ambalavasi"},
         { value:38, label: "Amma Kodava"},
         { value:40, label: "Anjana (Chowdary) Patel"},
         { value:42, label: "Arakh - Arakvanshiya"},
         { value:44, label: "Aramari - Gabit"},
         { value:46, label: "Arekatica"},
         { value:48, label: "Arora"},
         { value:50, label: "Arunthathiyar"},
         { value:52, label: "Arya Vysya"},
         { value:54, label: "Asathi"},
         { value:56, label: "Ayira Vysya"},
         { value:58, label: "Ayodhyavasi"},
         { value:60, label: "Ayyaraka"},
         { value:62, label: "Badaga"},
         { value:64, label: "Bagdi"},
         { value:66, label: "Baidya"},
         { value:68, label: "Bairwa"},
         { value:70, label: "Baishnab"},
         { value:72, label: "Baishya"},
         { value:74, label: "Bajantri"},
         { value:76, label: "Balai"},
         { value:78, label: "Balija"},
         { value:80, label: "Balija Naidu"},
         { value:82, label: "Balija Reddy"},
         { value:84, label: "Banayat Oriya"},
         { value:86, label: "Banik"},
         { value:88, label: "Baniya"},
         { value:90, label: "Baniya - Bania"},
         { value:92, label: "Baniya - Kumuti"},
         { value:94, label: "Banjara"},
         { value:96, label: "Barai"},
         { value:98, label: "Bari"},
         { value:100, label: "Baria"},
         { value:102, label: "Barnwal"},
         { value:104, label: "Barujibi"},
         { value:106, label: "Beri Chettiar"},
         { value:108, label: "Besta"},
         { value:110, label: "Bhandari"},
         { value:112, label: "Bhatia"},
         { value:114, label: "Bhatraju"},
         { value:116, label: "Bhavasar Kshatriya"},
         { value:118, label: "Bhil"},
         { value:120, label: "Bhoi"},
         { value:122, label: "Bhovi"},
         { value:124, label: "Bhoyar"},
         { value:126, label: "Bhulia - Meher"},
         { value:128, label: "Billava"},
         { value:130, label: "Bishnoi-Vishnoi"},
         { value:132, label: "Bondili"},
         { value:134, label: "Boyar"},
         { value:136, label: "Brahmakshtriya"},
         { value:138, label: "Brahmbatt"},
         { value:140, label: "Brahmin - Anavil"},
         { value:142, label: "Brahmin - Anaviln Desai"},
         { value:144, label: "Brahmin - Audichya"},
         { value:146, label: "Brahmin - Baidhiki-Vaidhiki"},
         { value:148, label: "Brahmin - Bardai"},
         { value:150, label: "Brahmin - Barendra"},
         { value:152, label: "Brahmin - Bhargav"},
         { value:154, label: "Brahmin - Bhatt"},
         { value:156, label: "Brahmin - Bhumihar"},
         { value:158, label: "Brahmin - Dadhich"},
         { value:160, label: "Brahmin - Daivadnya"},
         { value:162, label: "Brahmin - Danua"},
         { value:164, label: "Brahmin - Deshastha"},
         { value:166, label: "Brahmin - Dhiman"},
         { value:168, label: "Brahmin - Dravida"},
         { value:170, label: "Brahmin - Embrandiri"},
         { value:172, label: "Brahmin - Garhwali"},
         { value:174, label: "Brahmin - Gaur"},
         { value:176, label: "Brahmin - Goswami-Gosavi"},
         { value:178, label: "Brahmin - Gujar Gaur"},
         { value:180, label: "Brahmin - Gurukkal"},
         { value:182, label: "Brahmin - Halua"},
         { value:184, label: "Brahmin - Havyaka"},
         { value:186, label: "Brahmin - Hoysala"},
         { value:188, label: "Brahmin - Iyengar"},
         { value:190, label: "Brahmin - Iyer"},
         { value:192, label: "Brahmin - Jangid"},
         { value:194, label: "Brahmin - Jhadua"},
         { value:196, label: "Brahmin - Jyotish"},
         { value:198, label: "Brahmin - Kanyakubj"},
         { value:200, label: "Brahmin - Karhade"},
         { value:202, label: "Brahmin - Khadayata"},
         { value:204, label: "Brahmin - Khandelwal"},
         { value:206, label: "Brahmin - Khedaval"},
         { value:208, label: "Brahmin - Kokanastha"},
         { value:210, label: "Brahmin - Kota"},
         { value:212, label: "Brahmin - Koteshwara - Kota (Madhwa )"},
         { value:214, label: "Brahmin - Kulin"},
         { value:216, label: "Brahmin - Kumaoni"},
         { value:218, label: "Brahmin - Madhwa"},
         { value:220, label: "Brahmin - Maithil"},
         { value:222, label: "Brahmin - Mevada"},
         { value:224, label: "Brahmin - Modh"},
         { value:226, label: "Brahmin - Mohyal"},
         { value:228, label: "Brahmin - Nagar"},
         { value:230, label: "Brahmin - Namboodiri"},
         { value:232, label: "Brahmin - Narmadiya "},
         { value:234, label: "Brahmin - Niyogi"},
         { value:236, label: "Brahmin - Other"},
         { value:238, label: "Brahmin - Paliwal"},
         { value:240, label: "Brahmin - Panda"},
         { value:242, label: "Brahmin - Pandit"},
         { value:244, label: "Brahmin - Panicker"},
         { value:246, label: "Brahmin - Pareek"},
         { value:248, label: "Brahmin - Pushkarna"},
         { value:250, label: "Brahmin - Rajgor"},
         { value:252, label: "Brahmin - Rarhi"},
         { value:254, label: "Brahmin - Rarhi-Radhi"},
         { value:256, label: "Brahmin - Rigvedi"},
         { value:258, label: "Brahmin - Rudraj"},
         { value:260, label: "Brahmin - Sakaldwipi"},
         { value:262, label: "Brahmin - Sanadya"},
         { value:264, label: "Brahmin - Sanketi"},
         { value:266, label: "Brahmin - Saraswat"},
         { value:268, label: "Brahmin - Sarua"},
         { value:270, label: "Brahmin - Saryuparin"},
         { value:272, label: "Brahmin - Shivalli (Madhva)"},
         { value:274, label: "Brahmin - Shivhalli"},
         { value:276, label: "Brahmin - Shri Gaud"},
         { value:278, label: "Brahmin - Shri Mali"},
         { value:280, label: "Brahmin - Shrimali"},
         { value:282, label: "Brahmin - Shukla Yajurvedi"},
         { value:284, label: "Brahmin - Sikhwal"},
         { value:286, label: "Brahmin - Smartha"},
         { value:288, label: "Brahmin - Sri Vaishnava"},
         { value:290, label: "Brahmin - Stanika"},
         { value:292, label: "Brahmin - Tapodhan"},
         { value:294, label: "Brahmin - Tyagi"},
         { value:296, label: "Brahmin - Vaidiki"},
         { value:298, label: "Brahmin - Vaikhanasa"},
         { value:300, label: "Brahmin - Valam"},
         { value:302, label: "Brahmin - Velanadu"},
         { value:304, label: "Brahmin - Vyas"},
         { value:306, label: "Brahmin - Zalora"},
         { value:308, label: "Brajastha Maithil"},
         { value:310, label: "Brajastha Maithil"},
         { value:312, label: "Bunt (Shetty)"},
         { value:314, label: "CKP"},
         { value:316, label: "Chakkala Nair"},
         { value:318, label: "Chalawadi and Holeya"},
         { value:320, label: "Chambhar"},
         { value:322, label: "Chandravanshi Kahar"},
         { value:324, label: "Charan"},
         { value:326, label: "Chasa"},
         { value:328, label: "Chattada Sri Vaishnava "},
         { value:330, label: "Chaturth"},
         { value:332, label: "Chaudary"},
         { value:334, label: "Chaurasia"},
         { value:336, label: "Chennadasar"},
         { value:338, label: "Cherakula Vellalar"},
         { value:340, label: "Chettiar"},
         { value:342, label: "Chhetri"},
         { value:344, label: "Chippolu (Mera)"},
         { value:346, label: "Choudhary"},
         { value:348, label: "Coorgi"},
         { value:350, label: "Dasapalanjika - Kannada Saineegar"},
         { value:352, label: "Deshmukh"},
         { value:354, label: "Desikar"},
         { value:356, label: "Desikar Thanjavur"},
         { value:358, label: "Devadiga"},
         { value:360, label: "Devandra Kula Vellalar"},
         { value:362, label: "Devang Koshthi"},
         { value:364, label: "Devanga"},
         { value:366, label: "Devanga Chettiar"},
         { value:368, label: "Devar-Thevar-Mukkulathor"},
         { value:370, label: "Devrukhe Brahmin"},
         { value:372, label: "Dhanak"},
         { value:374, label: "Dhangar"},
         { value:376, label: "Dheevara"},
         { value:378, label: "Dhiman"},
         { value:380, label: "Dhoba"},
         { value:382, label: "Dhobi"},
         { value:384, label: "Dhor - Kakkayya"},
         { value:386, label: "Dommala"},
         { value:388, label: "Dosar - Dusra"},
         { value:390, label: "Dumal"},
         { value:392, label: "Dusadh (Paswan)"},
         { value:394, label: "Ediga"},
         { value:396, label: "Ediga -Goud (Balija)"},
         { value:398, label: "Elur Chetty"},
         { value:400, label: "Ezhava"},
         { value:402, label: "Ezhava Panicker"},
         { value:404, label: "Ezhava Thandan"},
         { value:406, label: "Ezhuthachan"},
         { value:408, label: "Gabit"},
         { value:410, label: "Gahoi"},
         { value:412, label: "Gajula - Kavarai"},
         { value:414, label: "Ganda"},
         { value:416, label: "Gandha Vanika"},
         { value:418, label: "Gandla"},
         { value:420, label: "Gandla - Ganiga"},
         { value:422, label: "Ganiga"},
         { value:424, label: "Garhwali"},
         { value:426, label: "Gatti"},
         { value:428, label: "Gavandi"},
         { value:430, label: "Gavara"},
         { value:432, label: "Gawali"},
         { value:434, label: "Ghisadi"},
         { value:436, label: "Ghumar"},
         { value:438, label: "Goala"},
         { value:440, label: "Goan"},
         { value:442, label: "Gomantak"},
         { value:444, label: "Gond"},
         { value:446, label: "Gondhali"},
         { value:448, label: "Gopal - Gopala"},
         { value:450, label: "Goud"},
         { value:452, label: "Gounder"},
         { value:454, label: "Gounder - Kongu Vellala Gounder"},
         { value:456, label: "Gounder - Nattu Gounder"},
         { value:458, label: "Gounder - Others"},
         { value:460, label: "Gounder - Urali Gounder"},
         { value:462, label: "Gounder - Vanniya Kula Kshatriyar"},
         { value:464, label: "Gounder - Vettuva Gounder"},
         { value:466, label: "Gowda"},
         { value:468, label: "Gowda - Kuruba Gowda"},
         { value:470, label: "Gramani"},
         { value:472, label: "Gudia"},
         { value:474, label: "Gujjar"},
         { value:476, label: "Gulahre"},
         { value:478, label: "Gupta"},
         { value:480, label: "Guptan"},
         { value:482, label: "Gurav"},
         { value:484, label: "Gurjar"},
         { value:486, label: "Haihaivanshi"},
         { value:488, label: "Halba Koshti"},
         { value:490, label: "Heggade"},
         { value:492, label: "Helava"},
         { value:494, label: "Holar"},
         { value:496, label: "Hugar (Jeer)"},
         { value:498, label: "Illaththu Pillai"},
         { value:500, label: "Intercaste"},
         { value:502, label: "Irani"},
         { value:504, label: "Isai Vellalar"},
         { value:506, label: "Jaalari"},
         { value:508, label: "Jaiswal"},
         { value:510, label: "Jandra"},
         { value:512, label: "Jangam"},
         { value:514, label: "Jangra - Brahmin"},
         { value:516, label: "Jat"},
         { value:518, label: "Jatav"},
         { value:520, label: "Jetty-Malla"},
         { value:522, label: "Jhadav"},
         { value:524, label: "Jijhotia Brahmin"},
         { value:526, label: "Jogi (Nath)"},
         { value:528, label: "Julaha"},
         { value:530, label: "Kachara"},
         { value:532, label: "Kadava Patel"},
         { value:534, label: "Kadia"},
         { value:536, label: "Kahar"},
         { value:538, label: "Kaibarta"},
         { value:540, label: "Kaikaala"},
         { value:542, label: "Kalal"},
         { value:544, label: "Kalanji"},
         { value:546, label: "Kalar"},
         { value:548, label: "Kalinga"},
         { value:550, label: "Kalinga Vysya"},
         { value:552, label: "Kalita"},
         { value:554, label: "Kalwar"},
         { value:556, label: "Kamboj"},
         { value:558, label: "Kamma"},
         { value:560, label: "Kamma Naidu"},
         { value:562, label: "Kanakkan Padanna"},
         { value:564, label: "Kandara"},
         { value:566, label: "Kansari"},
         { value:568, label: "Kansyakaar"},
         { value:570, label: "Kanykubj Bania"},
         { value:572, label: "Kapu"},
         { value:574, label: "Kapu Naidu"},
         { value:576, label: "Kapu Reddy"},
         { value:578, label: "Karakala Bhakthula"},
         { value:580, label: "Karana"},
         { value:582, label: "Karkathar"},
         { value:584, label: "Karmakar"},
         { value:586, label: "Karni Bhakthula"},
         { value:588, label: "Karuneegar"},
         { value:590, label: "Kasar"},
         { value:592, label: "Kasaundhan"},
         { value:594, label: "Kashyap"},
         { value:596, label: "Kasukara"},
         { value:598, label: "Katiya"},
         { value:600, label: "Kavara"},
         { value:602, label: "Kavuthiyya-Ezhavathy"},
         { value:604, label: "Kayastha"},
         { value:606, label: "Kayastha (Bengali)"},
         { value:608, label: "Kerala Mudali"},
         { value:610, label: "Keshri (Kesarwani)"},
         { value:612, label: "Khandayat"},
         { value:614, label: "Khandelwal"},
         { value:616, label: "Kharwa"},
         { value:618, label: "Kharwar"},
         { value:620, label: "Khatik"},
         { value:622, label: "Khatri"},
         { value:624, label: "Kirar"},
         { value:626, label: "Kodava"},
         { value:628, label: "Kodikal Pillai"},
         { value:630, label: "Kokanastha Maratha"},
         { value:632, label: "Koli"},
         { value:634, label: "Koli Mahadev"},
         { value:636, label: "Koli Patel"},
         { value:638, label: "Komti -Arya Vaishya"},
         { value:640, label: "Kongu Chettiar"},
         { value:642, label: "Kongu Nadar"},
         { value:644, label: "Kongu Vellala Gounder"},
         { value:646, label: "Konkani"},
         { value:648, label: "Korama"},
         { value:650, label: "Kori"},
         { value:652, label: "Kori-Koli"},
         { value:654, label: "Kosthi"},
         { value:656, label: "Krishnavaka"},
         { value:658, label: "Kshatriya"},
         { value:660, label: "Kshatriya Kurmi"},
         { value:662, label: "Kshatriya Raju"},
         { value:664, label: "Kudumbi"},
         { value:666, label: "Kulal"},
         { value:668, label: "Kulalar"},
         { value:670, label: "Kuli Maratha"},
         { value:672, label: "Kulita"},
         { value:674, label: "Kumaoni Rajput"},
         { value:676, label: "Kumawat"},
         { value:678, label: "Kumbhakar"},
         { value:680, label: "Kumbhar"},
         { value:682, label: "Kumhar"},
         { value:684, label: "Kummari"},
         { value:686, label: "Kunbi"},
         { value:688, label: "Kunbi Lonari"},
         { value:690, label: "Kunbi Maratha"},
         { value:692, label: "Kunbi Tirale"},
         { value:694, label: "Kuravan"},
         { value:696, label: "Kurmi"},
         { value:698, label: "Kurmi-Kurmi Kshatriya"},
         { value:700, label: "Kurni"},
         { value:702, label: "Kuruba"},
         { value:704, label: "Kuruhina Shetty"},
         { value:706, label: "Kuruhini Chetty"},
         { value:708, label: "Kurumbar"},
         { value:710, label: "Kuruva"},
         { value:712, label: "Kushwaha (Koiri)"},
         { value:714, label: "Kutchi"},
         { value:716, label: "Lad"},
         { value:718, label: "Lambadi"},
         { value:720, label: "Laxminarayan gola"},
         { value:722, label: "Leva patel"},
         { value:724, label: "Leva patil"},
         { value:726, label: "Linga Balija"},
         { value:728, label: "Lingayath"},
         { value:730, label: "Lodhi Rajput"},
         { value:732, label: "Lohana"},
         { value:734, label: "Lohar"},
         { value:736, label: "Loniya"},
         { value:738, label: "Lubana"},
         { value:740, label: "Madhesiya-Kanu-Halwai"},
         { value:742, label: "Madiga"},
         { value:744, label: "Mahajan"},
         { value:746, label: "Mahar"},
         { value:748, label: "Mahendra"},
         { value:750, label: "Maheshwari"},
         { value:752, label: "Maheshwari - Meshri"},
         { value:754, label: "Mahishya"},
         { value:756, label: "Mahor"},
         { value:758, label: "Mahuri"},
         { value:760, label: "Mair Rajput Swarnkar"},
         { value:762, label: "Majabi"},
         { value:764, label: "Mala"},
         { value:766, label: "Mali"},
         { value:768, label: "Mallah"},
         { value:770, label: "Malviya Brahmin"},
         { value:772, label: "Malwani"},
         { value:774, label: "Manai Telugu Chettiar"},
         { value:776, label: "Mangalorean"},
         { value:778, label: "Manipuri"},
         { value:780, label: "Manjapudur Chettiar"},
         { value:782, label: "Mannadiyar"},
         { value:784, label: "Mannan - Velan - Vannan"},
         { value:786, label: "Mapila"},
         { value:788, label: "Maratha"},
         { value:790, label: "Maratha Kshatriya"},
         { value:792, label: "Maruthuvar"},
         { value:794, label: "Matang"},
         { value:796, label: "Mathur"},
         { value:798, label: "Mathur Vaishya"},
         { value:800, label: "Matia Patel"},
         { value:802, label: "Maurya - Shakya"},
         { value:804, label: "Meena"},
         { value:806, label: "Meenavar"},
         { value:808, label: "Meghwal"},
         { value:810, label: "Mehra"},
         { value:812, label: "Meru Darji"},
         { value:814, label: "Mochi"},
         { value:816, label: "Modak"},
         { value:818, label: "Modh Ghanchi"},
         { value:820, label: "Modi"},
         { value:822, label: "Modikarlu"},
         { value:824, label: "Mogaveera"},
         { value:826, label: "Mudaliyar"},
         { value:828, label: "Mudiraj"},
         { value:830, label: "Munnuru Kapu"},
         { value:832, label: "Musukama"},
         { value:834, label: "Muthuraja"},
         { value:836, label: "Naagavamsam"},
         { value:838, label: "Nabit"},
         { value:840, label: "Nadar"},
         { value:842, label: "Nagaralu"},
         { value:844, label: "Nai - Nayi Brahmin"},
         { value:846, label: "Naicker"},
         { value:848, label: "Naicker - Others"},
         { value:850, label: "Naicker - Vanniya Kula Kshatriyar"},
         { value:852, label: "Naidu"},
         { value:854, label: "Naik"},
         { value:856, label: "Nair"},
         { value:858, label: "Namasudra - Namassej"},
         { value:860, label: "Nambiar"},
         { value:862, label: "Namdarlu"},
         { value:864, label: "Nanjil Mudali"},
         { value:866, label: "Nanjil Nattu Vellalar"},
         { value:868, label: "Nanjil Vellalar"},
         { value:870, label: "Nanjil pillai"},
         { value:872, label: "Nankudi Vellalar"},
         { value:874, label: "Napit"},
         { value:876, label: "Nattu Gounder"},
         { value:878, label: "Nattukottai Chettiar"},
         { value:880, label: "Nayaka"},
         { value:882, label: "Neeli"},
         { value:884, label: "Neeli Saali"},
         { value:886, label: "Nema"},
         { value:888, label: "Nepali"},
         { value:890, label: "Nessi"},
         { value:892, label: "Nhavi"},
         { value:894, label: "Niari"},
         { value:896, label: "Odan"},
         { value:898, label: "Ontari"},
         { value:900, label: "Oraon"},
         { value:902, label: "Oswal"},
         { value:904, label: "Otari"},
         { value:906, label: "Othuvaar"},
         { value:908, label: "Padmasali"},
         { value:910, label: "Padmashali"},
         { value:912, label: "Padmavati Porwal"},
         { value:914, label: "Pagadala"},
         { value:916, label: "Pal"},
         { value:918, label: "Pallan - Devandra Kula Vellalan"},
         { value:920, label: "Panan"},
         { value:922, label: "Panchal"},
         { value:924, label: "Pandaram"},
         { value:926, label: "Pandiya Vellalar"},
         { value:928, label: "Panicker"},
         { value:930, label: "Pannirandam Chettiar"},
         { value:932, label: "Paravan - Bharatar"},
         { value:934, label: "Parit"},
         { value:936, label: "Parkavakulam - Udayar"},
         { value:938, label: "Parsi"},
         { value:940, label: "Partraj"},
         { value:942, label: "Parvatha Rajakulam"},
         { value:944, label: "Pasi"},
         { value:946, label: "Paswan - Dusadh"},
         { value:948, label: "Patel"},
         { value:950, label: "Pathare Prabhu"},
         { value:952, label: "Patil"},
         { value:954, label: "Patnaick-Sistakaranam"},
         { value:956, label: "Patra"},
         { value:958, label: "Pattinavar"},
         { value:960, label: "Pattusali"},
         { value:962, label: "Patwa"},
         { value:964, label: "Perika"},
         { value:966, label: "Perika-Puragiri Kshatriya"},
         { value:968, label: "Pillai"},
         { value:970, label: "Poddar"},
         { value:972, label: "Poosala"},
         { value:974, label: "Porwal"},
         { value:976, label: "Porwal - Porwar"},
         { value:978, label: "Poundra"},
         { value:980, label: "Prajapati"},
         { value:982, label: "Pulaya -  Cheruman"},
         { value:984, label: "Radhi-Niari"},
         { value:986, label: "Raigar"},
         { value:988, label: "Rajaka - Vannar"},
         { value:990, label: "Rajastani"},
         { value:992, label: "Rajbhar"},
         { value:994, label: "Rajbonshi"},
         { value:996, label: "Rajpurohit"},
         { value:998, label: "Rajput"},
         { value:1000, label: "Raju - Kshatriya Raju"},
         { value:1002, label: "Ramanandi"},
         { value:1004, label: "Ramdasia"},
         { value:1006, label: "Ramgariah"},
         { value:1008, label: "Ramoshi"},
         { value:1010, label: "Rastogi"},
         { value:1012, label: "Rathi"},
         { value:1014, label: "Rauniar"},
         { value:1016, label: "Ravidasia"},
         { value:1018, label: "Rawat"},
         { value:1020, label: "Reddy"},
         { value:1022, label: "Relli"},
         { value:1024, label: "Rohit - Chamar"},
         { value:1026, label: "Ror"},
         { value:1028, label: "SC"},
         { value:1030, label: "SKP"},
         { value:1032, label: "ST"},
         { value:1034, label: "Sadgope"},
         { value:1036, label: "Sadhu Chetty"},
         { value:1038, label: "Sagara (Uppara)"},
         { value:1040, label: "Saha"},
         { value:1042, label: "Sahu"},
         { value:1044, label: "Saini"},
         { value:1046, label: "Saiva Pillai Thanjavur"},
         { value:1048, label: "Saiva Pillai Tirunelveli"},
         { value:1050, label: "Saiva Vellan chettiar"},
         { value:1052, label: "Saliya"},
         { value:1054, label: "Saliyar"},
         { value:1056, label: "Samagar"},
         { value:1058, label: "Sambava"},
         { value:1060, label: "Sathwara"},
         { value:1062, label: "Satnami"},
         { value:1064, label: "Savji"},
         { value:1066, label: "Senai Thalaivar"},
         { value:1068, label: "Senguntha Mudaliyar"},
         { value:1070, label: "Sengunthar-Kaikolar"},
         { value:1072, label: "Settibalija"},
         { value:1074, label: "Setty Balija"},
         { value:1076, label: "Shah"},
         { value:1078, label: "Shaw - Sahu-Teli"},
         { value:1080, label: "Shettigar"},
         { value:1082, label: "Shilpkar"},
         { value:1084, label: "Shimpi-Namdev"},
         { value:1086, label: "Sindhi"},
         { value:1088, label: "Sindhi - Amil"},
         { value:1090, label: "Sindhi - Baibhand"},
         { value:1092, label: "Sindhi - Bhanusali"},
         { value:1094, label: "Sindhi - Bhatia"},
         { value:1096, label: "Sindhi - Chhapru"},
         { value:1098, label: "Sindhi - Dadu"},
         { value:1100, label: "Sindhi - Hyderabadi"},
         { value:1102, label: "Sindhi - Larai"},
         { value:1104, label: "Sindhi - Larkana"},
         { value:1106, label: "Sindhi - Lohana"},
         { value:1108, label: "Sindhi - Rohiri"},
         { value:1110, label: "Sindhi - Sahiti"},
         { value:1112, label: "Sindhi - Sakkhar"},
         { value:1114, label: "Sindhi - Sehwani"},
         { value:1116, label: "Sindhi - Shikarpuri"},
         { value:1118, label: "Sindhi - Thatai"},
         { value:1120, label: "Sonar"},
         { value:1122, label: "Soni"},
         { value:1124, label: "Sonkar"},
         { value:1126, label: "Sourashtra"},
         { value:1128, label: "Sozhia Chetty"},
         { value:1130, label: "Sozhiya Vellalar"},
         { value:1132, label: "Srisayana"},
         { value:1134, label: "Sugali (Naika)"},
         { value:1136, label: "Sunari"},
         { value:1138, label: "Sundhi"},
         { value:1140, label: "Surya Balija"},
         { value:1142, label: "Suthar"},
         { value:1144, label: "Swakula Sali"},
         { value:1146, label: "Swarnakar"},
         { value:1148, label: "Tamboli"},
         { value:1150, label: "Tammali"},
         { value:1152, label: "Tanti"},
         { value:1154, label: "Tantubai"},
         { value:1156, label: "Telaga"},
         { value:1158, label: "Teli"},
         { value:1160, label: "Telugupatti"},
         { value:1162, label: "Thakkar"},
         { value:1164, label: "Thakore"},
         { value:1166, label: "Thakur"},
         { value:1168, label: "Thandan"},
         { value:1170, label: "Tharakan"},
         { value:1172, label: "Thigala"},
         { value:1174, label: "Thiyya"},
         { value:1176, label: "Thiyya Thandan"},
         { value:1178, label: "Thogata Veera Kshatriya"},
         { value:1180, label: "Thogata Veerakshathriya"},
         { value:1182, label: "Thondai Mandala Vellalar"},
         { value:1184, label: "Thota"},
         { value:1186, label: "Tili"},
         { value:1188, label: "Togata"},
         { value:1190, label: "Tonk Kshatriya"},
         { value:1192, label: "Turupu Kapu"},
         { value:1194, label: "Ummar - Umre - Bagaria"},
         { value:1196, label: "Urali Gounder"},
         { value:1198, label: "Urs"},
         { value:1200, label: "Vada Balija"},
         { value:1202, label: "Vadambar"},
         { value:1204, label: "Vadar"},
         { value:1206, label: "Vaddera"},
         { value:1208, label: "Vadugan"},
         { value:1210, label: "Vaish"},
         { value:1212, label: "Vaishnav"},
         { value:1214, label: "Vaishnav Dishaval"},
         { value:1216, label: "Vaishnav Kapol"},
         { value:1218, label: "Vaishnav Khadyata"},
         { value:1220, label: "Vaishnav Lad"},
         { value:1222, label: "Vaishnav Modh"},
         { value:1224, label: "Vaishnav Porvad"},
         { value:1226, label: "Vaishnav Shrimali"},
         { value:1228, label: "Vaishnav Sorathaiya"},
         { value:1230, label: "Vaishnav Vania"},
         { value:1232, label: "Vaishnava"},
         { value:1234, label: "Vaishya"},
         { value:1236, label: "Vaishya Vani"},
         { value:1238, label: "Valar"},
         { value:1240, label: "Valluvan"},
         { value:1242, label: "Valmiki"},
         { value:1244, label: "Valsad"},
         { value:1246, label: "Vani"},
         { value:1248, label: "Vani - Vaishya"},
         { value:1250, label: "Vania"},
         { value:1252, label: "Vanika Vyshya"},
         { value:1254, label: "Vaniya"},
         { value:1256, label: "Vaniya Chettiar"},
         { value:1258, label: "Vanjara"},
         { value:1260, label: "Vanjari"},
         { value:1262, label: "Vankar"},
         { value:1264, label: "Vannar"},
         { value:1266, label: "Vannia Kula Kshatriyar"},
         { value:1268, label: "Vanyakulakshatriya"},
         { value:1270, label: "Variar"},
         { value:1272, label: "Varshney"},
         { value:1274, label: "Varshney (Barahseni)"},
         { value:1276, label: "Veera Saivam"},
         { value:1278, label: "Veerakodi Vellala"},
         { value:1280, label: "Velaan"},
         { value:1282, label: "Velama"},
         { value:1284, label: "Vellala Pillai"},
         { value:1286, label: "Vellalar"},
         { value:1288, label: "Vellan Chettiars"},
         { value:1290, label: "Veluthedathu Nair"},
         { value:1292, label: "Vettuva Gounder"},
         { value:1294, label: "Vettuvan"},
         { value:1296, label: "Vijayvargia"},
         { value:1298, label: "Vilakithala Nair"},
         { value:1300, label: "Vilakkithala Nair"},
         { value:1302, label: "Vishwakarma"},
         { value:1304, label: "Viswabrahmin"},
         { value:1306, label: "Vokkaliga"},
         { value:1308, label: "Vysya"},
         { value:1310, label: "Yadav"},
         { value:1312, label: "Yadava Naidu"},
         { value:1314, label: "Yellapu"}
     ],       
     dhoshamValues :[
        { value: "-", label: "--Nil--" },
        { value: "C", label: "Chevvai dosham" },
        { value: "N", label: "Naga dosham Kala" },
        { value: "R", label: "Rahu dosham" },
        { value: "R", label: "Sarpa dosham" },
        { value: "K", label: "Kethu dosham" },
        { value: "A", label: "Kalathra dosham" },
      ]    
}